config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  # Section for user dashboard START
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions, :passwords, :confirmations, :registrations]
  devise_scope :user do

    # session handling
    get     '/my/dashboard/login'  => 'devise/sessions#new',     as: 'new_user_session'
    post    '/my/dashboard/login'  => 'devise/sessions#create',  as: 'user_session'
    delete  '/my/dashboard/logout' => 'devise/sessions#destroy', as: 'destroy_user_session'

    # joining
    get   '/my/dashboard/join' => 'devise/registrations#new',    as: 'new_user_registration'
    post  '/my/dashboard/join' => 'devise/registrations#create', as: 'user_registration'
    put   '/my/dashboard/join' => 'devise/registrations#update'
    delete '/my/dashboard/join' => 'devise/registrations#destroy'

    scope '/my/dashboard/account' do
      # password reset
      get   '/reset-password'        => 'devise/passwords#new',    as: 'new_user_password'
      put   '/reset-password'        => 'devise/passwords#update', as: 'user_password'
      post  '/reset-password'        => 'devise/passwords#create'
      get   '/reset-password/change' => 'devise/passwords#edit',   as: 'edit_user_password'

      # confirmation
      get   '/confirm'        => 'devise/confirmations#show',   as: 'user_confirmation'
      post  '/confirm'        => 'devise/confirmations#create'
      get   '/confirm/resend' => 'devise/confirmations#new',    as: 'new_user_confirmation'

      # settings & cancellation
      get '/cancel'   => 'devise/registrations#cancel', as: 'cancel_user_registration'
      get '/settings' => 'devise/registrations#edit',   as: 'edit_user_registration'
      put '/settings' => 'devise/registrations#update'

      # account deletion
      delete '' => 'devise/registrations#destroy'#, as: 'delete_user_registration'
    end
  end
  # Section for user dashboard END

  get '/my', to: redirect('/my/dashboard'), as: 'my_index'
  get '/my/dashboard', to: 'user_cabinet#index', as: 'user_cabinet_index'
  get '/my/dashboard/history', to: 'user_cabinet#history', as: 'user_cabinet_history'
  get '/my/dashboard/subscribe', to: 'user_cabinet#subscribe', as: 'user_cabinet_subscribe'
  get '/my/dashboard/feedback', to: 'user_cabinet#feedback', as: 'user_cabinet_feedback'

  # Restorans START
  get '/my/dashboard/restorans', to: 'restoran#index', as: 'my_restoran_index'
  get '/my/dashboard/restorans/new', to: 'restoran#new', as: 'my_restoran_new'
  post '/my/dashboard/restorans', to: 'restoran#create', as: 'my_restoran_create'
  get '/my/dashboard/restorans/:id/edit', to: 'restoran#edit', as: 'my_restoran_edit'
  delete '/my/dashboard/restorans/:id', to: 'restoran#destroy', as: 'my_restoran_delete'
  put '/my/dashboard/restorans/:id', to: 'restoran#update', as: 'my_restoran_update'
  patch '/my/dashboard/restorans/:id', to: 'restoran#update', as: 'my_restoran_path_update'
  # Restorans END

  # Catalogs START
  get '/my/dashboard/catalogs', to: 'catalog#index', as: 'my_catalog_index'
  get '/my/dashboard/catalogs/new', to: 'catalog#new', as: 'my_catalog_new'
  post '/my/dashboard/catalogs', to: 'catalog#create', as: 'my_catalog_create'
  get '/my/dashboard/catalogs/:id/edit', to: 'catalog#edit', as: 'my_catalog_edit'
  delete '/my/dashboard/catalogs/:id', to: 'catalog#destroy', as: 'my_catalog_delete'
  put '/my/dashboard/catalogs/:id', to: 'catalog#update', as: 'my_catalog_update'
  patch '/my/dashboard/catalogs/:id', to: 'catalog#update', as: 'my_catalog_path_update'
  # Catalogs END

  # Products START
  get '/my/dashboard/products', to: 'product#index', as: 'my_product_index'
  get '/my/dashboard/products/new', to: 'product#new', as: 'my_product_new'
  post '/my/dashboard/products', to: 'product#create', as: 'my_product_create'
  get '/my/dashboard/products/:id/edit', to: 'product#edit', as: 'my_product_edit'
  delete '/my/dashboard/products/:id', to: 'product#destroy', as: 'my_product_delete'
  put '/my/dashboard/products/:id', to: 'product#update', as: 'my_product_update'
  patch '/my/dashboard/products/:id', to: 'product#update', as: 'my_product_path_update'
  # Products END

  # Orders START
  get '/my/dashboard/orders', to: 'order#index', as: 'my_order_index'
  #get '/my/dashboard/orders/new', to: 'order#new', as: 'my_order_new'
  #post '/my/dashboard/orders', to: 'order#create', as: 'my_order_create'
  get '/my/dashboard/orders/:id/edit', to: 'order#edit', as: 'my_order_edit'
  delete '/my/dashboard/orders/:id', to: 'order#destroy', as: 'my_order_delete'
  put '/my/dashboard/orders/:id', to: 'order#update', as: 'my_order_update'
  patch '/my/dashboard/orders/:id', to: 'order#update', as: 'my_order_path_update'


  get '/order', to: 'page#order', as: 'order_index'
  get '/order/create', to: 'page#new_order', as: 'order_new'
  post '/order/submit', to: 'page#submit_order', as: 'order_submit'


  get '/restoran/:id', to: 'page#restorans_item', as: 'restorans_item'
  get '/restoran/:restoran_id/:id', to: 'page#catalogs_item', as: 'products_by_category'

  # Orders END

  root 'page#index'
end

app/controllers/user_cabinet_controller.rb
class UserCabinetController < ApplicationController
  #before_filter :ensure_signup_complete, only: [:index, :show, :edit, :update, :destroy]
  before_action :authenticate_user! #, only: [:index, :show, :edit, :update, :destroy]

  add_breadcrumb "<span>//</span> Особистий кабінет".html_safe, :my_index_path

  def index
    add_breadcrumb "Мій профайл", :user_cabinet_index_path
  end

  def history
    add_breadcrumb "Історія покупок", :user_cabinet_history_path
    @history = Order.where(user_id: current_user.id)
  end

  def subscribe
    add_breadcrumb "Підписка на розсилку", :user_cabinet_subscribe_path
  end

  def feedback
    add_breadcrumb "Залишити відгук", :user_cabinet_subscribe_path
  end

end

app/helpers/user_cabinet_helper.rb
module UserCabinetHelper
end

app/views/partials/user_cabinet/_side_menu.html.erb
<%- if current_user.admin? || current_user.order_manager? %>
  <ul id="admin-menu">
    <li <%- if controller_name == "restoran" && action_name == "index" || controller_name == 'restoran' && action_name == 'edit' || controller_name == 'restoran' && action_name == 'new' || controller_name == 'restoran' && action_name == 'create' || controller_name == 'restoran' && action_name == 'show' || controller_name == 'restoran' && action_name == 'update' %> class="current" <% end -%>><%= link_to 'Ресторани', my_restoran_index_path  %></li>
    <li <%- if controller_name == "catalog" && action_name == "index" || controller_name == 'catalog' && action_name == 'edit' || controller_name == 'catalog' && action_name == 'new' || controller_name == 'catalog' && action_name == 'create' || controller_name == 'catalog' && action_name == 'show' || controller_name == 'catalog' && action_name == 'update' %> class="current" <% end -%>><%= link_to 'Каталог їжі', my_catalog_index_path  %></li>
    <li <%- if controller_name == "product" && action_name == "index" || controller_name == 'product' && action_name == 'edit' || controller_name == 'product' && action_name == 'new' || controller_name == 'product' && action_name == 'create' || controller_name == 'product' && action_name == 'show' || controller_name == 'product' && action_name == 'update' %> class="current" <% end -%>><%= link_to 'Їжа', my_product_index_path  %></li>
    <li <%- if controller_name == "order" && action_name == "index" || controller_name == 'order' && action_name == 'edit' || controller_name == 'order' && action_name == 'new' || controller_name == 'order' && action_name == 'create' || controller_name == 'order' && action_name == 'show' || controller_name == 'order' && action_name == 'update' %> class="current" <% end -%>><%= link_to 'Замовлення', my_order_index_path %></li>
    <li><%= link_to 'Бали' %></li>
    <li><%= link_to 'Зворотній виклик' %></li>
    <li <%- if controller_name == "user_cabinet" && action_name == "index" %> class="current" <% end -%> ><%= link_to "Мій профіль", user_cabinet_index_path %></li>
    <li <%- if controller_name == "user_cabinet" && action_name == "history" %> class="current" <% end -%> ><%= link_to "Історія покупок", user_cabinet_history_path %></li>
    <li <%- if controller_name == "user_cabinet" && action_name == "subscribe" %> class="current" <% end -%> ><%= link_to "Підписка на розсилку", user_cabinet_subscribe_path %></li>
    <li <%- if controller_name == "user_cabinet" && action_name == "feedback" %> class="current" <% end -%>><%= link_to 'Залишити відгук', user_cabinet_feedback_path %></li>
  </ul>
<% else %>
<ul>
  <li <%- if controller_name == "user_cabinet" && action_name == "index" %> class="current" <% end -%> ><%= link_to "Мій профіль", user_cabinet_index_path %></li>
  <li <%- if controller_name == "user_cabinet" && action_name == "history" %> class="current" <% end -%> ><%= link_to "Історія покупок", user_cabinet_history_path %></li>
  <li <%- if controller_name == "user_cabinet" && action_name == "subscribe" %> class="current" <% end -%> ><%= link_to "Підписка на розсилку", user_cabinet_subscribe_path %></li>
  <li <%- if controller_name == "user_cabinet" && action_name == "feedback" %> class="current" <% end -%>><%= link_to 'Залишити відгук', user_cabinet_feedback_path %></li>
</ul>
<% end -%>