config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  # Section for user dashboard START
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions, :passwords, :confirmations, :registrations]
  devise_scope :user do

    # session handling
    get     '/my/dashboard/login'  => 'devise/sessions#new',     as: 'new_user_session'
    post    '/my/dashboard/login'  => 'devise/sessions#create',  as: 'user_session'
    delete  '/my/dashboard/logout' => 'devise/sessions#destroy', as: 'destroy_user_session'

    # joining
    get   '/my/dashboard/join' => 'devise/registrations#new',    as: 'new_user_registration'
    post  '/my/dashboard/join' => 'devise/registrations#create', as: 'user_registration'
    put   '/my/dashboard/join' => 'devise/registrations#update'
    delete '/my/dashboard/join' => 'devise/registrations#destroy'

    scope '/my/dashboard/account' do
      # password reset
      get   '/reset-password'        => 'devise/passwords#new',    as: 'new_user_password'
      put   '/reset-password'        => 'devise/passwords#update', as: 'user_password'
      post  '/reset-password'        => 'devise/passwords#create'
      get   '/reset-password/change' => 'devise/passwords#edit',   as: 'edit_user_password'

      # confirmation
      get   '/confirm'        => 'devise/confirmations#show',   as: 'user_confirmation'
      post  '/confirm'        => 'devise/confirmations#create'
      get   '/confirm/resend' => 'devise/confirmations#new',    as: 'new_user_confirmation'

      # settings & cancellation
      get '/cancel'   => 'devise/registrations#cancel', as: 'cancel_user_registration'
      get '/settings' => 'devise/registrations#edit',   as: 'edit_user_registration'
      put '/settings' => 'devise/registrations#update'

      # account deletion
      delete '' => 'devise/registrations#destroy'#, as: 'delete_user_registration'
    end
  end
  # Section for user dashboard END

  get '/my', to: redirect('/my/dashboard'), as: 'my_index'
  get '/my/dashboard', to: 'user_cabinet#index', as: 'user_cabinet_index'
  get '/my/dashboard/history', to: 'user_cabinet#history', as: 'user_cabinet_history'
  get '/my/dashboard/subscribe', to: 'user_cabinet#subscribe', as: 'user_cabinet_subscribe'
  get '/my/dashboard/feedback', to: 'user_cabinet#feedback', as: 'user_cabinet_feedback'

  # Restorans START
  get '/my/dashboard/restorans', to: 'restoran#index', as: 'my_restoran_index'
  get '/my/dashboard/restorans/new', to: 'restoran#new', as: 'my_restoran_new'
  post '/my/dashboard/restorans', to: 'restoran#create', as: 'my_restoran_create'
  get '/my/dashboard/restorans/:id/edit', to: 'restoran#edit', as: 'my_restoran_edit'
  delete '/my/dashboard/restorans/:id', to: 'restoran#destroy', as: 'my_restoran_delete'
  put '/my/dashboard/restorans/:id', to: 'restoran#update', as: 'my_restoran_update'
  patch '/my/dashboard/restorans/:id', to: 'restoran#update', as: 'my_restoran_path_update'
  # Restorans END

  # Catalogs START
  get '/my/dashboard/catalogs', to: 'catalog#index', as: 'my_catalog_index'
  get '/my/dashboard/catalogs/new', to: 'catalog#new', as: 'my_catalog_new'
  post '/my/dashboard/catalogs', to: 'catalog#create', as: 'my_catalog_create'
  get '/my/dashboard/catalogs/:id/edit', to: 'catalog#edit', as: 'my_catalog_edit'
  delete '/my/dashboard/catalogs/:id', to: 'catalog#destroy', as: 'my_catalog_delete'
  put '/my/dashboard/catalogs/:id', to: 'catalog#update', as: 'my_catalog_update'
  patch '/my/dashboard/catalogs/:id', to: 'catalog#update', as: 'my_catalog_path_update'
  # Catalogs END

  # Products START
  get '/my/dashboard/products', to: 'product#index', as: 'my_product_index'
  get '/my/dashboard/products/new', to: 'product#new', as: 'my_product_new'
  post '/my/dashboard/products', to: 'product#create', as: 'my_product_create'
  get '/my/dashboard/products/:id/edit', to: 'product#edit', as: 'my_product_edit'
  delete '/my/dashboard/products/:id', to: 'product#destroy', as: 'my_product_delete'
  put '/my/dashboard/products/:id', to: 'product#update', as: 'my_product_update'
  patch '/my/dashboard/products/:id', to: 'product#update', as: 'my_product_path_update'
  # Products END

  # Orders START
  get '/my/dashboard/orders', to: 'order#index', as: 'my_order_index'
  #get '/my/dashboard/orders/new', to: 'order#new', as: 'my_order_new'
  #post '/my/dashboard/orders', to: 'order#create', as: 'my_order_create'
  get '/my/dashboard/orders/:id/edit', to: 'order#edit', as: 'my_order_edit'
  delete '/my/dashboard/orders/:id', to: 'order#destroy', as: 'my_order_delete'
  put '/my/dashboard/orders/:id', to: 'order#update', as: 'my_order_update'
  patch '/my/dashboard/orders/:id', to: 'order#update', as: 'my_order_path_update'


  get '/order', to: 'page#order', as: 'order_index'
  get '/order/create', to: 'page#new_order', as: 'order_new'
  post '/order/submit', to: 'page#submit_order', as: 'order_submit'


  get '/restoran/:id', to: 'page#restorans_item', as: 'restorans_item'
  get '/restoran/:restoran_id/:id', to: 'page#catalogs_item', as: 'products_by_category'

  # Orders END

  root 'page#index'
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  before_action :authenticate_user!
  before_action :get_admin
  before_action :set_catalog, only: [:show, :edit, :update, :destroy]

  add_breadcrumb "<span>//</span> Особистий кабінет".html_safe, :my_index_path

  def index
    add_breadcrumb "Каталог їжі", :my_catalog_index_path
    @catalogs = Category.all
  end

  def show
    add_breadcrumb "Каталог їжі", :my_catalog_index_path
  end

  def new
    add_breadcrumb "Каталог їжі", :my_catalog_index_path
    add_breadcrumb "Новий"
    @catalog = Category.new
  end

  def edit
    add_breadcrumb "Каталог їжі", :my_catalog_index_path
    add_breadcrumb "Редагувати"
  end

  def create
    @catalog = Category.new(catalog_params)

    respond_to do |format|
      if @catalog.save
        format.html { redirect_to my_catalog_index_path, notice: 'Restoran was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @catalog.update(catalog_params)
        format.html { redirect_to my_catalog_index_url, notice: 'Restoran was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @catalog.destroy
    respond_to do |format|
      format.html { redirect_to my_catalog_index_url, notice: 'Restoran was successfully destroyed.' }
    end
  end

  private

  def get_admin
    unless current_user.admin? || current_user.order_manager?
      redirect_to my_index_path, :notice => "Access denied."
    end
  end


  # Use callbacks to share common setup or constraints between actions.
  def set_catalog
    @catalog = Category.find_by_slug!(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def catalog_params
    params.require(:category).permit(:name, :slug, :restoran, :restoran_id)
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/views/catalog/_edit_form.html.erb
<%= simple_form_for(@catalog, url: my_catalog_update_path) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: "Назва", input_html: {placeholder: 'Піца'}, hint: "Назва категорії їжі" %>
  <%= f.input :slug, label: "Силка", input_html: {placeholder: 'pizza'}, hint: "Силка для відображення url", as: :hidden %>
  <%= f.association :restoran, label: "Ресторан", hint: "Вкажіть для якого ресторану" %>
  <%= f.submit "Зберегти", class: 'submit-btn' %>
<% end %>

app/views/catalog/_form.html.erb
<%= simple_form_for(@catalog, url: my_catalog_index_path) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: "Назва", input_html: {placeholder: 'Піца'}, hint: "Назва категорії їжі" %>
  <%= f.input :slug, label: "Силка", input_html: {placeholder: 'pizza'}, hint: "Силка для відображення url", as: :hidden %>
  <%= f.association :restoran, label: "Ресторан", hint: "Вкажіть для якого ресторану" %>
  <%= f.submit "Зберегти", class: 'submit-btn' %>
<% end %>

app/views/catalog/edit.html.erb
<section id="dashboard">
  <div id="dashboard-container">
    <div id="dashboard-row">
      <div class="dashboard-navigation">
        <%= render partial: 'partials/user_cabinet/side_menu' %>
      </div>
      <section id="dashboard-user-profile">
        <h2>Каталог їжі</h2>
        <%= render 'edit_form' %>
        <br>
        <%= link_to 'Назад', my_catalog_index_path, class: 'back' %>
      </section>
    </div>
  </div>
</section>

app/views/catalog/index.html.erb
<section id="dashboard">
  <div id="dashboard-container">
    <div id="dashboard-row">

      <div class="dashboard-navigation">
        <%= render partial: 'partials/user_cabinet/side_menu' %>
      </div>

      <section id="dashboard-user-profile">
        <%# if notice %>
          <script type="text/javascript" charset="utf-8">
            document = function(){
              swal("Молодец!", "Категорія їжі успішно сворена!");
            };
          </script>
        <%# end %>
        <h2>Каталог їжі</h2>
        <table class="table table-responsive">
          <thead>
          <tr>
            <th>Назва</th>
            <th>Ресторан</th>
            <th colspan="2"></th>
          </tr>
          </thead>

          <tbody>
          <% @catalogs.each do |catalog| %>
            <tr>
              <td><%= catalog.name %></td>
              <td><%= catalog.restoran.name %></td>
              <td><%= link_to 'Редагувати', my_catalog_edit_path(catalog), class: 'submit-btn' %></td>
              <td><%= link_to 'Видалити', my_catalog_delete_path(catalog), method: :delete, data: { confirm: 'Ви впевненні?' }, class: 'submit-btn' %></td>
            </tr>
          <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'Додати новий', my_catalog_new_path, class: 'back' %>
      </section>

    </div>
  </div>
</section>

app/views/catalog/new.html.erb
<section id="dashboard">
  <div id="dashboard-container">
    <div id="dashboard-row">
      <div class="dashboard-navigation">
        <%= render partial: 'partials/user_cabinet/side_menu' %>
      </div>
      <section id="dashboard-user-profile">
        <h2>Каталог їжі</h2>
        <%= render 'form' %>
        <br>
        <%= link_to 'Назад', my_catalog_index_path, class: 'back' %>
      </section>
    </div>
  </div>
</section>

app/views/catalog/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restoran.name %>
</p>

<%= link_to 'Edit', edit_restoran_path(@restoran) %> |
<%= link_to 'Back', restoran_path %>