config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  # Section for user dashboard START
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }, skip: [:sessions, :passwords, :confirmations, :registrations]
  devise_scope :user do

    # session handling
    get     '/my/dashboard/login'  => 'devise/sessions#new',     as: 'new_user_session'
    post    '/my/dashboard/login'  => 'devise/sessions#create',  as: 'user_session'
    delete  '/my/dashboard/logout' => 'devise/sessions#destroy', as: 'destroy_user_session'

    # joining
    get   '/my/dashboard/join' => 'devise/registrations#new',    as: 'new_user_registration'
    post  '/my/dashboard/join' => 'devise/registrations#create', as: 'user_registration'
    put   '/my/dashboard/join' => 'devise/registrations#update'
    delete '/my/dashboard/join' => 'devise/registrations#destroy'

    scope '/my/dashboard/account' do
      # password reset
      get   '/reset-password'        => 'devise/passwords#new',    as: 'new_user_password'
      put   '/reset-password'        => 'devise/passwords#update', as: 'user_password'
      post  '/reset-password'        => 'devise/passwords#create'
      get   '/reset-password/change' => 'devise/passwords#edit',   as: 'edit_user_password'

      # confirmation
      get   '/confirm'        => 'devise/confirmations#show',   as: 'user_confirmation'
      post  '/confirm'        => 'devise/confirmations#create'
      get   '/confirm/resend' => 'devise/confirmations#new',    as: 'new_user_confirmation'

      # settings & cancellation
      get '/cancel'   => 'devise/registrations#cancel', as: 'cancel_user_registration'
      get '/settings' => 'devise/registrations#edit',   as: 'edit_user_registration'
      put '/settings' => 'devise/registrations#update'

      # account deletion
      delete '' => 'devise/registrations#destroy'#, as: 'delete_user_registration'
    end
  end
  # Section for user dashboard END

  get '/my', to: redirect('/my/dashboard'), as: 'my_index'
  get '/my/dashboard', to: 'user_cabinet#index', as: 'user_cabinet_index'
  get '/my/dashboard/history', to: 'user_cabinet#history', as: 'user_cabinet_history'
  get '/my/dashboard/subscribe', to: 'user_cabinet#subscribe', as: 'user_cabinet_subscribe'
  get '/my/dashboard/feedback', to: 'user_cabinet#feedback', as: 'user_cabinet_feedback'

  # Restorans START
  get '/my/dashboard/restorans', to: 'restoran#index', as: 'my_restoran_index'
  get '/my/dashboard/restorans/new', to: 'restoran#new', as: 'my_restoran_new'
  post '/my/dashboard/restorans', to: 'restoran#create', as: 'my_restoran_create'
  get '/my/dashboard/restorans/:id/edit', to: 'restoran#edit', as: 'my_restoran_edit'
  delete '/my/dashboard/restorans/:id', to: 'restoran#destroy', as: 'my_restoran_delete'
  put '/my/dashboard/restorans/:id', to: 'restoran#update', as: 'my_restoran_update'
  patch '/my/dashboard/restorans/:id', to: 'restoran#update', as: 'my_restoran_path_update'
  # Restorans END

  # Catalogs START
  get '/my/dashboard/catalogs', to: 'catalog#index', as: 'my_catalog_index'
  get '/my/dashboard/catalogs/new', to: 'catalog#new', as: 'my_catalog_new'
  post '/my/dashboard/catalogs', to: 'catalog#create', as: 'my_catalog_create'
  get '/my/dashboard/catalogs/:id/edit', to: 'catalog#edit', as: 'my_catalog_edit'
  delete '/my/dashboard/catalogs/:id', to: 'catalog#destroy', as: 'my_catalog_delete'
  put '/my/dashboard/catalogs/:id', to: 'catalog#update', as: 'my_catalog_update'
  patch '/my/dashboard/catalogs/:id', to: 'catalog#update', as: 'my_catalog_path_update'
  # Catalogs END

  # Products START
  get '/my/dashboard/products', to: 'product#index', as: 'my_product_index'
  get '/my/dashboard/products/new', to: 'product#new', as: 'my_product_new'
  post '/my/dashboard/products', to: 'product#create', as: 'my_product_create'
  get '/my/dashboard/products/:id/edit', to: 'product#edit', as: 'my_product_edit'
  delete '/my/dashboard/products/:id', to: 'product#destroy', as: 'my_product_delete'
  put '/my/dashboard/products/:id', to: 'product#update', as: 'my_product_update'
  patch '/my/dashboard/products/:id', to: 'product#update', as: 'my_product_path_update'
  # Products END

  # Orders START
  get '/my/dashboard/orders', to: 'order#index', as: 'my_order_index'
  #get '/my/dashboard/orders/new', to: 'order#new', as: 'my_order_new'
  #post '/my/dashboard/orders', to: 'order#create', as: 'my_order_create'
  get '/my/dashboard/orders/:id/edit', to: 'order#edit', as: 'my_order_edit'
  delete '/my/dashboard/orders/:id', to: 'order#destroy', as: 'my_order_delete'
  put '/my/dashboard/orders/:id', to: 'order#update', as: 'my_order_update'
  patch '/my/dashboard/orders/:id', to: 'order#update', as: 'my_order_path_update'


  get '/order', to: 'page#order', as: 'order_index'
  get '/order/create', to: 'page#new_order', as: 'order_new'
  post '/order/submit', to: 'page#submit_order', as: 'order_submit'


  get '/restoran/:id', to: 'page#restorans_item', as: 'restorans_item'
  get '/restoran/:restoran_id/:id', to: 'page#catalogs_item', as: 'products_by_category'

  # Orders END

  root 'page#index'
end

app/models/product.rb
# coding: utf-8
require 'unicode'

class Product < ActiveRecord::Base

  attr_accessible :name, :slug, :price, :description, :point, :avatar, :category, :category_id, :category_attributes, :unit

  has_and_belongs_to_many :orders, join_table: 'product_orders'
  belongs_to :category

  before_validation :friendly_url
  before_save :normalize_name

  default_scope { order('created_at DESC') }
  scope :asc, -> { order('created_at ASC') }

  validates :name, presence: true
  validates :slug, uniqueness: true
  validates :price, presence: true
  #validates :description, presence: true
  #validates :point, presence: true
  #validates :avatar, presence: true
  #validates :category, presence: true

  has_attached_file :avatar, styles:{
                               thumb: '60x60#',
                               thumb_pr: '120x120#',
                               main: '238x238#',
                               main_big: '682x320#',
                               main_big_square: '1024x820#'
                           },
                    convert_options:{
                        thumb: '-quality 80 -interlace Plane',
                        thumb_pr: '-quality 80 -interlace Plane',
                        main: '-quality 80 -interlace Plane',
                        main_big: '-quality 80 -interlace Plane',
                        main_big_square: '-quality 80 -interlace Plane'
                    },
                    default_url: "/assets/images/food/:style/missing.jpg",
                    url:'/assets/images/food/:class/:id/image_:style.:extension',
                    path:':rails_root/public:url'

  validates_attachment :avatar, content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif', 'image/svg+xml'] }

  accepts_nested_attributes_for :category

  def to_param
    slug
  end

  def image_slug
    return name.parameterize if name
    "unknown"
  end

  def friendly_url
    self.slug = [(category.name).parameterize, (price.to_s).parameterize, name.parameterize].join("-")
  end

  def normalize_name
    self.name = Unicode::capitalize(name)
  end

  def percent_of(n)
    self.to_f / n.to_f * 10.0
  end

  def ceil2(exp = 0)
    multiplier = 10 ** exp
    ((self * multiplier).ceil).to_f/multiplier.to_f
  end

  def calculate_points
    self.point = (percent_of(price)).round
  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  # Before user tried to access controller check auth
  before_action :authenticate_user!
  # If user has admin roles
  before_action :get_admin
  # Set product method
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # Add default breadcrumb
  add_breadcrumb "<span>//</span> Особистий кабінет".html_safe, :my_index_path

  # Index page
  # /my/dashboard/products
  def index
    add_breadcrumb "Їжа", :my_product_index_path
    @products = Product.paginate(:page => params[:page], :per_page => 10)
  end

  # New product page
  # /my/dashboard/products/new
  def new
    add_breadcrumb "Їжа", :my_product_index_path
    add_breadcrumb "Новий"
    @product = Product.new
  end

  def edit
    add_breadcrumb "Їжа", :my_product_index_path
    add_breadcrumb "Редагувати"
  end

  def create
    @product = Product.new(catalog_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to my_product_index_path, notice: 'Restoran was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(catalog_params)
        format.html { redirect_to my_product_index_url, notice: 'Restoran was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to my_product_index_url, notice: 'Restoran was successfully destroyed.' }
    end
  end

  private

  def get_admin
    unless current_user.admin? || current_user.order_manager?
      redirect_to my_index_path, :notice => "Access denied."
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find_by_slug!(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def catalog_params
    params.require(:product).permit(:name, :slug, :price, :description, :point, :avatar, :category, :category_id, :category_attributes, :unit)
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/_edit_form.html.erb
<%= simple_form_for(@product, url: my_product_update_path) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: "Назва", input_html: {placeholder: 'Піца'}, hint: "Назва ресторан" %>
  <%= f.input :slug, :disabled => true, label: "Силка", input_html: {placeholder: 'pizza'}, hint: "Силка для відображення url, генерується автоматично", as: :hidden %>
  <%= f.input :avatar, label: "Головне зображеня", as: :image_preview %>
  <%= f.input :price, label: "Ціна", input_html: {placeholder: '20,25'}, hint: "Ціна за одиницю товару" %>
  <%= f.input :unit, label: "Одиниця виміру", input_html: { placeholder: '20 гр' }, hint: '' %>
  <%= f.input :description, label: "Опис", input_html: {placeholder: 'морква, бульба, цибуля'}, hint: "Компоненти страви" %>
  <%= f.input :point, label: "Бали", input_html: {placeholder: '10'}, hint: "Бали за 1 куплену одиницю товару" %>
  <%= f.association :category, :label_method => lambda { |category| "#{category.restoran.name} > #{category.name}" } %>
  <%= f.submit "Зберегти", class: 'submit-btn' %>
<% end %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    $('#product_category_id').selectize({
      delimiter: ',',
      persist: false,
      create: function(input) {
        return {
          value: input,
          text: input
        }
      }
    });
  });
</script>

app/views/product/_form.html.erb
<%= simple_form_for(@product, url: my_product_index_path) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: "Назва", input_html: {placeholder: 'Піца'}, hint: "Назва ресторан" %>
  <%= f.input :slug, :disabled => true, label: "Силка", input_html: {placeholder: 'pizza'}, hint: "Силка для відображення url, генерується автоматично", as: :hidden %>
  <%= f.input :avatar, label: "Головне зображеня", as: :image_preview %>
  <%= f.input :price, label: "Ціна", input_html: {placeholder: '20,25'}, hint: "Ціна за одиницю товару" %>
  <%= f.input :unit, label: "Одиниця виміру", input_html: { placeholder: '20 гр' }, hint: '' %>
  <%= f.input :description, label: "Опис", input_html: {placeholder: 'морква, бульба, цибуля'}, hint: "Компоненти страви" %>
  <%= f.input :point, label: "Бали", input_html: {placeholder: '10'}, hint: "Бали за 1 куплену одиницю товару" %>
  <%= f.association :category, :label_method => lambda { |category| "#{category.restoran.name} > #{category.name}" } %>
  <%= f.submit "Зберегти", class: 'submit-btn' %>
<% end %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    $('#product_category_id').selectize({
      delimiter: ',',
      persist: false,
      create: function(input) {
        return {
          value: input,
          text: input
        }
      }
    });
  });
</script>

app/views/product/edit.html.erb
<section id="dashboard">
  <div id="dashboard-container">
    <div id="dashboard-row">
      <div class="dashboard-navigation">
        <%= render partial: 'partials/user_cabinet/side_menu' %>
      </div>
      <section id="dashboard-user-profile">
        <h2>Їжа</h2>
        <%= render 'edit_form' %>
        <br>
        <%= link_to 'Назад', my_product_index_path, class: 'back' %>
      </section>
    </div>
  </div>
</section>

app/views/product/index.html.erb
<section id="dashboard">
  <div id="dashboard-container">
    <div id="dashboard-row">

      <div class="dashboard-navigation">
        <%= render partial: 'partials/user_cabinet/side_menu' %>
      </div>

      <section id="dashboard-user-profile">
        <% if notice %>
          <div id="notification">
            <p><%= notice %></p>
          </div>
          <script type="text/javascript" charset="utf-8">
            $(document).ready(function(e){
              var $notification = $("#notification");
              setTimeout(function() {
                $notification.fadeOut("slow");
              }, 4000);
            });
          </script>
        <% end %>
        <h2>Їжа</h2>
        <table class="table table-responsive">
          <thead>
          <tr>
            <th>Зображеня</th>
            <th>Назва</th>
            <th>Ціна</th>
            <th>Ресторан</th>
            <th>Категорія</th>
            <th colspan="2"></th>
          </tr>
          </thead>

          <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= image_tag product.avatar.url(:thumb) %></td>
              <td><%= product.name %></td>
              <td><%= product.price %></td>
              <td><%= product.category.name %></td>
              <td><%= product.category.restoran.name %></td>
              <td><%= link_to 'Редагувати', my_product_edit_path(product), class: 'submit-btn' %></td>
              <td><%= link_to 'Видалити', my_product_delete_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'submit-btn' %></td>
            </tr>
          <% end %>
          </tbody>
        </table>

        <%= will_paginate @products %>
        <br>

        <%= link_to 'Додати новий', my_product_new_path, class: 'back' %>
      </section>

    </div>
  </div>
</section>

app/views/product/new.html.erb
<section id="dashboard">
  <div id="dashboard-container">
    <div id="dashboard-row">
      <div class="dashboard-navigation">
        <%= render partial: 'partials/user_cabinet/side_menu' %>
      </div>
      <section id="dashboard-user-profile">
        <h2>Їжа</h2>
        <%= render 'form' %>
        <br>
        <%= link_to 'Назад', my_product_index_path, class: 'back' %>
      </section>
    </div>
  </div>
</section>